name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -q
          sudo apt-get install -y libboost-dev libboost-tools-dev libboost-json-dev libssl-dev libsqlite3-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
            brew install boost boost-build openssl sqlite
            echo "using darwin ;" >>~/user-config.jam

      - name: Build
        run: b2 webtorrent=on
